name: location_report_app
description: A location-based reporting app.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  image_picker: ^1.1.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.5.0
  uuid: ^4.3.3
  video_player: ^2.8.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
